
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package proyecto.compiladores;

import java_cup.runtime.Symbol;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class CodigoCup extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public CodigoCup() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public CodigoCup(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public CodigoCup(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\004\000\002\002\004\000\002\002\004\000\002\002" +
    "\003\000\002\003\005" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\010\000\004\005\004\001\002\000\004\004\011\001" +
    "\002\000\006\002\uffff\005\004\001\002\000\004\002\007" +
    "\001\002\000\004\002\001\001\002\000\004\002\000\001" +
    "\002\000\004\005\012\001\002\000\006\002\ufffe\005\ufffe" +
    "\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\010\000\006\002\005\003\004\001\001\000\002\001" +
    "\001\000\006\002\007\003\004\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$CodigoCup$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$CodigoCup$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$CodigoCup$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$CodigoCup$actions {
  private final CodigoCup parser;

  /** Constructor */
  CUP$CodigoCup$actions(CodigoCup parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$CodigoCup$do_action_part00000000(
    int                        CUP$CodigoCup$act_num,
    java_cup.runtime.lr_parser CUP$CodigoCup$parser,
    java.util.Stack            CUP$CodigoCup$stack,
    int                        CUP$CodigoCup$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$CodigoCup$result;

      /* select the action based on the action number */
      switch (CUP$CodigoCup$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= S EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$CodigoCup$stack.elementAt(CUP$CodigoCup$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$CodigoCup$stack.elementAt(CUP$CodigoCup$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$CodigoCup$stack.elementAt(CUP$CodigoCup$top-1)).value;
		RESULT = start_val;
              CUP$CodigoCup$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$CodigoCup$stack.elementAt(CUP$CodigoCup$top-1)), ((java_cup.runtime.Symbol)CUP$CodigoCup$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$CodigoCup$parser.done_parsing();
          return CUP$CodigoCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // S ::= I S 
            {
              Object RESULT =null;
		 System.out.println("S -> I S");
              CUP$CodigoCup$result = parser.getSymbolFactory().newSymbol("S",0, ((java_cup.runtime.Symbol)CUP$CodigoCup$stack.elementAt(CUP$CodigoCup$top-1)), ((java_cup.runtime.Symbol)CUP$CodigoCup$stack.peek()), RESULT);
            }
          return CUP$CodigoCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // S ::= I 
            {
              Object RESULT =null;
		 System.out.println("S -> I");
              CUP$CodigoCup$result = parser.getSymbolFactory().newSymbol("S",0, ((java_cup.runtime.Symbol)CUP$CodigoCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$CodigoCup$stack.peek()), RESULT);
            }
          return CUP$CodigoCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // I ::= ID MAS ID 
            {
              Object RESULT =null;
		 System.out.println("I -> ID MAS ID");
              CUP$CodigoCup$result = parser.getSymbolFactory().newSymbol("I",1, ((java_cup.runtime.Symbol)CUP$CodigoCup$stack.elementAt(CUP$CodigoCup$top-2)), ((java_cup.runtime.Symbol)CUP$CodigoCup$stack.peek()), RESULT);
            }
          return CUP$CodigoCup$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$CodigoCup$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$CodigoCup$do_action(
    int                        CUP$CodigoCup$act_num,
    java_cup.runtime.lr_parser CUP$CodigoCup$parser,
    java.util.Stack            CUP$CodigoCup$stack,
    int                        CUP$CodigoCup$top)
    throws java.lang.Exception
    {
              return CUP$CodigoCup$do_action_part00000000(
                               CUP$CodigoCup$act_num,
                               CUP$CodigoCup$parser,
                               CUP$CodigoCup$stack,
                               CUP$CodigoCup$top);
    }
}

}
